### ISSUE TITLE
The plugin doesn't get initialized when running "sls offline start"

### ISSUE THREAD

**Issue by hakimio** [pidz-development/serverless-local-kinesis#2]
If it's supposed to just run when starting serverless offline `sls offline start`, then it doesn't seem to work. It doesn't log anything and  `kinesalite` is not started.

**Comment by hakimio** [comment]
@yooouuri Does this work with `serverless-plugin-typescript` instead of webpack plugin? Can you make a working example?

**Comment by hakimio** [comment]
@yooouuri and others experiencing the issue with the latest version of `serverless-offline` plugin, I found out what was the issue. 
It seems `serverless offline` hook has changed in new version. Instead of `before:offline:start`, it should be `before:offline:start:init`. 

As a temporary workaround [patch-package](https://github.com/ds300/patch-package) can be used to fix the plugin:
```diff
diff --git a/node_modules/serverless-local-kinesis/lib/index.js b/node_modules/serverless-local-kinesis/lib/index.js
index 3934e9e..66f4ab0 100644
--- a/node_modules/serverless-local-kinesis/lib/index.js
+++ b/node_modules/serverless-local-kinesis/lib/index.js
@@ -47,6 +47,7 @@ class ServerlessLocalKinesis {
         });
         this.hooks = {
             'before:offline:start': this.run.bind(this),
+            'before:offline:start:init': this.run.bind(this)
         };
     }
     async run() {

```

**Comment by yooouuri** [comment]
Hey @hakimio,

When I have some spare time, i'll update the package.

Thanks
